version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn war:exploded
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
      - mv target .
artifacts:
  type: zip
  files:
    - 'WEB-INF/classes/application.properties'
    - 'WEB-INF/classes/com/aws/codestar/projecttemplates/HelloWorldAppInitializer.class'
    - 'WEB-INF/classes/com/aws/codestar/projecttemplates/configuration/ApplicationConfig.class'
    - 'WEB-INF/classes/com/aws/codestar/projecttemplates/configuration/MvcConfig.class'
    - 'WEB-INF/classes/com/aws/codestar/projecttemplates/controller/HelloWorldController.class'
    - 'WEB-INF/lib/aopalliance-1.0.jar'
    - 'WEB-INF/lib/commons-fileupload-1.3.3.jar'
    - 'WEB-INF/lib/commons-io-2.5.jar'
    - 'WEB-INF/lib/commons-logging-1.2.jar'
    - 'WEB-INF/lib/javax.servlet-api-3.1.0.jar'
    - 'WEB-INF/lib/spring-aop-4.3.14.RELEASE.jar'
    - 'WEB-INF/lib/spring-beans-4.3.14.RELEASE.jar'
    - 'WEB-INF/lib/spring-context-4.3.14.RELEASE.jar'
    - 'WEB-INF/lib/spring-core-4.3.14.RELEASE.jar'
    - 'WEB-INF/lib/spring-expression-4.3.14.RELEASE.jar'
    - 'WEB-INF/lib/spring-web-4.3.14.RELEASE.jar'
    - 'WEB-INF/lib/spring-webmvc-4.3.14.RELEASE.jar'
    - 'WEB-INF/views/index.jsp'
    - 'resources/gradients.css'
    - 'resources/set-background.js'
    - 'resources/styles.css'
    - 'resources/tweet.svg'
